Text from http://caa-international.org/special-interest-groups/

## Special Interest Groups

The Special Interest Group (SIG) initiative was introduced at the 2001 Conference. CAA currently have three active SIGs:

- Complex Systems Simulation
- Education, Training and Outreach
- Computer Programs for Archaeologists

### Rules for Special Interest Groups

1. CAA will enable and encourage the formation of Special Interest Groups (SIG).

2. A Special Interest is defined here as covering the archaeological application of an area of computer and/or quantitative methods that is relevant to, and compatible with, the aims of CAA and is of current interest to a significant number of CAA members.

3. The primary function of a SIG will be to form a focus for discussion, dissemination and organisation of activities relating to the Special Interest topic.

4. SIGs may be formed by a group of CAA members with the consent of the Steering Committee and subject to ratification by the CAA Annual General Meeting. The group proposing the formation of a SIG must include at least two CAA members who must demonstrate that they are able to coordinate the activities of the proposed SIG and that the proposed Special Interest is of interest to a significant number of CAA members. The proposal to form a new SIG must include a description of the Special Interest, an outline of the proposed activities of the SIG and details of how the SIG is to be organised within the terms of para 6 below.

5. All members of CAA will be entitled to membership of any SIG. Members of a SIG will be entitled to take part in any of the activities of the SIG.

6. The day-to-day running of a SIG will be in the hands of a convenor and one or more other SIG members who together will form an ad hoc SIG committee. The group proposing the formation of a new SIG will form the initial committee. Arrangements for appointing the convenor and other members of the committee will be discussed and determined by SIG members within one year of receiving Steering Committee approval for the formation of the SIG and must be submitted to the next CAA Annual General Meeting for approval.

7. SIG convenors and other committee members may use the name of CAA in dealing with other individuals and organisations, but should ensure that their actions are commensurate with the aims of CAA and do not bring the name of CAA into disrepute.

8. The full name of a SIG shall be of the form ‘CAA xxSIG’ or ‘CAA SIGxx’ where ‘xx’ is one or more characters conveying the primary topic of the SIG.

9. A SIG may be dissolved at any time, subject to the approval of the Steering Committee. The SIG committee should notify the Steering Committee of its intention to dissolve and should normally provide evidence that the dissolution is supported by a simple majority of the active members of the SIG.

### Notes

At the request of conference organisers, SIG convenors and other committee members will be expected to aid, advise and participate in the organization of SIG-specific sessions. They should also be prepared to act as referees and to locate other potential referees, both for the initial scrutiny of paper submissions, and for reviewing papers submitted for publication in conference proceedings and other CAA publications.

SIGs should make use of communication and dissemination methods provided for their use by CAA. CAA will ensure that SIGs have the opportunity to include material in its communications with members.

SIG Meetings may take any generally acceptable form, whether physical or virtual.

Interesting topics come and go, so should SIGs.