<div class = "ascii_art">

```
   _____ _____ _____    _____ _____ _              
  / ____|_   _/ ____|  / ____/ ____| |       /\
 | (___   | || |  __  | (___| (___ | |      /  \
  \___ \  | || | |_ |  \___ \\___ \| |     / /\ \
  ____) |_| || |__| |  ____) |___) | |___ / ____ \
 |_____/|_____\_____| |_____/_____/|_____/_/    \_\    

```
<!-- http://patorjk.com/software/taag/#p=author&f=Big&t=SIG%20SSLA -->
</div>

## Special Interest Group on Scientific Scripting Languages in Archaeology

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```

### Background

At the CAA 2018 Tübingen we had a session on R as archaeological tool. Within this session all papers showed a very high standard of utilisation of R for archaeological questions, and a huge variety of different approaches.

Lively discussions on teaching R to students and colleagues followed, and the question arose how we can make our preferred analytical framework more open and accessible to other interested parties.

From these events and discussions emerged a proposal to form a Special Interest Group (SIG) at CAA International to have a permanent platform to exchange and discuss ideas, and to develop the practical benefits of R for archaeological applications.

Following further discussion with colleagues it became clear that it would be a good idea to include other scripting languages, eg. python, into this SIG.

With this repository and these Github pages, in the spirit of open accessibility, transparency and reproducible science, we would like to start this process that will hopefully result in the formation of a SIG in Krakow 2019.

### What we will do

Within the next year we aim at installing the basic functionalities and drafting the basic documents needed to make a successful bid to CAA International to have this SIG accepted as official component of the CAA universe. This will include:

- a list of potential members and collaborators for the group
- an exchange platform for its members and also for the communication with the scientific/archaeological/general community
- a statement of purpose and scope of the SIG

We will discuss the topics, aims, challenges and structure of the SIG in a Roundtable at the Krakow 2019 CAA conference: [S03 -- Roundtable Scientific Scripting Languages in Archaeology - Limits and Opportunities of Open Research](https://ocs.caaconference.org/index.php?conference=caa&schedConf=CAA2019&page=schedConf&op=trackPolicies#track3)

### What you can do

If you are working in the field of quantitative archaeology, if you are using scripting languages as part of your analysis and daily work, and if you would like to contribute and take part in the decision making of this group, please feel free and encouraged to contact us on our <i class="fa fa-google"></i> [Google Mailing List](https://groups.google.com/forum/#!forum/scientific-scripting-languages-in-archaeology), or write us directly via our email address: <i class="fa fa-envelope"></i> [sig.sci.script.arch@gmail.com](mailto:sig.sci.script.arch@gmail.com)

