<div class = "ascii_art_wrapper">
<div class = "ascii_art">

```
    ,-----------------------------------,    
---(_\ ~~~~~~~ ~~~ ~~~~ ~~ ~~~~ ~~~~ ~~  \-- 
     | ~~ ~~ ~~~ ~~~~~ ~~~ ~~~ ~~ ~~~~~  |   
     | ~~~~ ~~~ ~~~~ ~~~~ ~~~ ~~~~ ~~~~  |   
     | ~~~ ~~~~~~~~~ ~~~~~~~~ ~~~ ~~ ~~  |   
    _|                      - SIG SSLA   |   
---(_/___________________________________/---



```
<!-- Inspiration: http://ascii.co.uk/art/scroll -->
</div>
</div>

## Statement of purpose

*The following 'statement of purpose' provides a basis for discussion, which is to be revised in consultation with the scientists involved.*

The purpose of the [CAA Special Interest Group](http://caa-international.org/special-interest-groups/) **Scientific Scripting Languages in Archaeology** is to promote the use of scripting languages in archaeology to better align the practice of archaeology with the goals of archaeological science. We will provide an exchange platform for scientists in and around archaeology who use scripting languages to conduct major or minor parts of their research. Scientific programming in non-scripting languages is not excluded, but this SIG focussed on software projects and data analysis work-flows that use code interactively. 

The Special Interest Group is an open format that is intended to support discussion, the circulation of new ideas, and the integration of different approaches in connection with the objectives. Everyone may participate on equal terms in accordance with the [Ethics Policy](http://caa-international.org/about/ethics-policy/) of CAA International. To ensure expedient and civil exchange, the SIG committee will remove, edit, or reject comments, commits, code, issues, and other contributions that are not aligned with this policy. To be as inclusive as possible and also for the sake of reproducibility we strongly prefer open source over proprietary software.

We especially invite students and young career researches to become part of a wider network of developers and users to improve their skills, and promote the use of scripting languages in research, publication and teaching in archaeology. Open and reproducible research is becoming increasingly important in all scientific disciplines. We have to avoid a "lost" generation of students in archaeology that can't keep pace with this development due to a lack of hard knowledge about computational tools and data exchange standards. The SIG aims to establish the career path of the research software engineer in archaeology.

### Scripting languages

A scripting language is a programming language which allows live coding interaction with an software interpreter to perform tasks with data. It does not require the compilation of a software module (or only requires this incidentally to the main coding activity) and it is therefore linked to a rapid development style especially suitable for scientific data exploration, analysis, and visualisation. The following list includes popular scripting languages in archaeology and many other sciences:

- [R](https://www.r-project.org/) 
- [Python](https://www.python.org/)
- [Bash](http://www.gnu.org/software/bash/)
- [Netlogo](https://ccl.northwestern.edu/netlogo/)
- [Stan](http://mc-stan.org/)
- [OxCal](https://c14.arch.ox.ac.uk/oxcal.html)
- [Observable](https://beta.observablehq.com/) (JavaScript)
- ...

The scopes and purposes of these scripting languages are highly different. Some of them (like R or Python) are fully capable programming languages which provide methods and libraries for all kind of cross-platform system- and network-interaction. Some (like OxCal) are rather specific collections of basic commands to control individual software tools and therefore serve as mere interfaces. Despite this differences both kind of scripting languages allow to create a reproducible representation of a scientific task.

### Reproducible research

The use of scripting languages for research allows the user to document every necessary step in a research pipeline. The resulting script can be used to reproduce the data analysis by other researchers, given that also the input datasets are provided and -- if necessary -- the required software environment can be emulated. Scripting languages are therefore the ideal for reproducible research. R and and Python for example provide specialised frameworks to combine data, code and text (R Markdown, Jupyter Notebooks, ...). Reproducible research is important for archaeology because it allows other researchers to verify published findings, and to easily extend new methods to other datasets. 

### Version control

Reproducible research ideally also documents the science production process with all inductive and deductive steps of hypothesis building. A modern and powerful way to store a commented succession of changes in text and scripted data analysis is available with tools like Git or SVN which where initially designed for software development. They provide a simple environment to keep track of even minor changes, go back to earlier working stages and allow for well documented collaborations thanks to forking. The combination of scripting languages and version control is an important basis for a fully comprehensible research process.

### Objectives of the SIG SSLA

Main objectives:

- Promote the use of scripting languages to replace widely-used black-box software with transparent and reproducible code written in open source languages. 
- Teach and provide teaching materials for scripting languages
- Discuss and comment on new developments in and for scripting languages
- Define best practice standards and guides for writing, sharing and publishing code
- Develop step-by-step pipelines for common archaeological tasks
- Construct a peer review network for code in publications and software libraries
- Establish an inheritance network to arrange long term maintenance and responsibility for software written by and for archaeologists

Additional possibilities:

- Set up a web platform for discussion
- Share news and announcements about the latest advanced publications using scripting languages, new software packages designed for archaeology, tutorials, seminars, conferences or summer schools via social media
- Set up a web platform for an archaeological [rosetta code](http://rosettacode.org) collection
- Work together on projects like collaboratively programming a custom software library
- Create an own scripting language designed just for archaeological purposes
